FROM openjdk:8
MAINTAINER rick1113 <chinmoy1113@gmail.com>
ADD target/notification-service-0.0.1-SNAPSHOT.jar notification-service.jar
ENTRYPOINT ["java", "-jar", "/notification-service.jar"]
EXPOSE 8404
