FROM openjdk:8
MAINTAINER rick1113 <chinmoy1113@gmail.com>
ADD target/authenticate-service-0.0.1-SNAPSHOT.jar authenticate-service.jar
ENTRYPOINT ["java", "-jar", "/authenticate-service.jar"]
EXPOSE 8400
